doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuidv7: Symfony\Bridge\Doctrine\Types\UuidV7Type
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true