doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Bareapi:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Bareapi/Entity'
                prefix: 'Bareapi\Entity'
                alias: Bareapi
