framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    csrf_protection: ~
    session:
        handler_id: null
    router:
        utf8: true
    # enable test service container and client
    test: true
