framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    csrf_protection: ~
    session:
        handler_id: null
    router:
        utf8: true
    cache:
        pools:
            doctrine.system_cache_pool:
                adapter: cache.adapter.array
            doctrine.result_cache_pool:
                adapter: cache.adapter.array
