<?php

declare(strict_types=1);

namespace Bareapi\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;

#[ORM\Entity]
#[ORM\Table(name: 'meta_object_revisions')]
#[ORM\Index(columns: ['uuid', 'revision'], name: 'idx_meta_object_revisions_uuid_revision')]
#[ORM\UniqueConstraint(name: 'uniq_object_revision', columns: ['uuid', 'revision'])]
class MetaObjectRevision
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column]
    /**
     * @phpstan-ignore property.unusedType (auto-generated by Doctrine)
     */
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: MetaObject::class, inversedBy: 'revisions')]
    #[ORM\JoinColumn(name: 'uuid', referencedColumnName: 'uuid', onDelete: 'CASCADE')]
    private MetaObject $metaObject;

    #[ORM\Column]
    private int $revision;

    #[ORM\Column(name: 'parent_id', type: 'uuid', nullable: true)]
    private ?UuidInterface $parentId = null;

    /**
     * @var array<string, mixed>
     */
    #[ORM\Column(type: 'jsonb')]
    private array $data;

    #[ORM\Column(name: 'created_at', type: Types::DATETIMETZ_IMMUTABLE)]
    private DateTimeImmutable $createdAt;

    #[ORM\Column(name: 'deleted_at', type: Types::DATETIMETZ_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $deletedAt = null;

    /**
     * @param array<string, mixed> $data
     */
    public function __construct(MetaObject $metaObject, int $revision, array $data)
    {
        $this->metaObject = $metaObject;
        $this->revision = $revision;
        $this->data = $data;
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMetaObject(): MetaObject
    {
        return $this->metaObject;
    }

    public function setMetaObject(MetaObject $metaObject): self
    {
        $this->metaObject = $metaObject;

        return $this;
    }

    public function getRevision(): int
    {
        return $this->revision;
    }

    public function setRevision(int $revision): self
    {
        $this->revision = $revision;

        return $this;
    }

    public function getParentId(): ?UuidInterface
    {
        return $this->parentId;
    }

    public function setParentId(?UuidInterface $parentId): self
    {
        $this->parentId = $parentId;

        return $this;
    }

    /**
     * @return array<string, mixed>
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param array<string, mixed> $data
     */
    public function setData(array $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getDeletedAt(): ?DateTimeImmutable
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?DateTimeImmutable $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    public function isDeleted(): bool
    {
        return $this->deletedAt !== null;
    }
}
