# Dynamic CRUD routes for all schema-defined object types
data_collection:
    path: /data/{type}
    controller: App\Controller\DataListController
    methods: [GET]
    requirements:
        type: '\\w+'

data_create:
    path: /data/{type}
    controller: App\Controller\DataCreateController
    methods: [POST]
    requirements:
        type: '\\w+'

data_item:
    path: /data/{type}/{id}
    controller: App\Controller\DataShowController
    methods: [GET]
    requirements:
        type: '\\w+'
        id: '[0-9a-fA-F\-]{36}'

data_update:
    path: /data/{type}/{id}
    controller: App\Controller\DataUpdateController
    methods: [PUT]
    requirements:
        type: '\\w+'
        id: '[0-9a-fA-F\-]{36}'

data_delete:
    path: /data/{type}/{id}
    controller: App\Controller\DataDeleteController
    methods: [DELETE]
    requirements:
        type: '\\w+'
        id: '[0-9a-fA-F\-]{36}'