index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirect
    defaults:
        path: /api
        permanent: true

controllers:
    resource: '../src/Controller/'
    type: annotation