parameters:
    env(APP_SECRET): 'change_me'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Bareapi\:
        resource: '../src/Bareapi/*'
        exclude: '../src/Bareapi/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Bareapi\Controller\:
        resource: '../src/Bareapi/Controller'
        tags: ['controller.service_arguments']

    Bareapi\Controller\DataCreateController:
        arguments:
            $validator: '@JsonSchema\\Validator'

    Bareapi\Controller\DataUpdateController:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    JsonSchema\Validator: ~
