parameters:
    env(APP_SECRET): 'change_me'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Bareapi\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Bareapi\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Bareapi\Controller\DataCreateController:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    Bareapi\Controller\DataUpdateController:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    JsonSchema\Validator: ~

    Bareapi\EventListener\ExceptionListener:
            arguments:
                $kernelEnvironment: '%kernel.environment%'
            tags:
                - { name: kernel.event_listener, event: kernel.exception }
