parameters:
    env(APP_SECRET): 'change_me'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Bareapi\Service\SchemaService:
        arguments:
            $schemaDir: '%kernel.project_dir%/config/schemas/'

    Bareapi\Repository\MetaObjectRepository:
        arguments:
            $schemaService: '@Bareapi\Service\SchemaService'

    Bareapi\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Bareapi\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']


    JsonSchema\Validator: ~

    Bareapi\EventListener\ExceptionListener:
            arguments:
                $kernelEnvironment: '%kernel.environment%'
            tags:
                - { name: kernel.event_listener, event: kernel.exception }
